name: Trigger auto deployment for container-app-c37jpdobzdjfi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-c37jpdobzdjfi-AutoDeployTrigger-4281608f-3327-469f-a0b7-849b2dc5402f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPC37JPDOBZDJFI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPC37JPDOBZDJFI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPC37JPDOBZDJFI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPC37JPDOBZDJFI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPC37JPDOBZDJFI_REGISTRY_PASSWORD }}
          containerAppName: container-app-c37jpdobzdjfi
          resourceGroup: appspacesragapp88dabeb2
          imageToBuild: default/container-app-c37jpdobzdjfi:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


